---
title: 'Kongen i Gult'
Subtitle: > 
    Dansk oversættelse af udvalgte noveller fra Robert W. Chambers 'The King in Yellow' til dansk. 
author:
- Robert W. Chambers
keywords: ebooks, Chambers
language: da-DK
tags: [the king in yellow, chambers]
cover-image: images/kongen-i-gult.png
lang: da
stylesheet: epub.css
publisher: http://gittobook.org
rights: http://creativecommons.org/licenses/by-sa/2.5/
date: 1895
# are exports private or not / only repo owner can download exports (epub, mobi)
private: true

# pandoc format arguments
# because of security these options are limited
format-arguments:
    #html: -S --chapters --toc
    pdf: -V documentclass=memoir --template=templates/default.latex -S --toc --chapters -V fontsize=13pt -V lang=danish
    epub: -S --toc --toc-depth=1
    mobi: ok
    html-chunked: -s -S
# ignore files
ignore-files:
    - README.md
...
