---
title: 'Kongen i Gult<br ><br />'
Subtitle: > 
    Dansk <br ><br>oversættelse af udvalgte noveller fra Robert W. Chambers 'The King in Yellow' til dansk. 
author:
- Robert W. Chambers
keywords: ebooks, Chambers<br/>
language: da-DK
tags: [the king in yellow, chambers<br/>]
cover-image: images/kongen-i-gult.png
lang: da
stylesheet: epub.css
publisher: http://gittobook.org
rights: http://creativecommons.org/licenses/by-sa/2.5/

# pandoc format arguments
# because of security these options are limited
format-arguments:
    #html: -S --chapters --toc
    epub: -S --toc --toc-depth=1
    mobi: ok
    html-chunked: -s -S
# ignore files
ignore-files:
    - README.md
...
